# Basic Data Types

# int: whole numbers (Positibe or negative)
age = 25
temperature = -5


# float: Decimal numbers
height = 5.9
weight = -3.14


# str: Text data, enclosed in quotes
greeting = "Hello, world!"


# bool: True or False values
is_active = True
is_verified = False


# Complex Data Types

# list: ordered, mutable collection
fruits = ["apple", "banana", "cherry"]


# tuple: ordered, immutable collection
coordinates = (10, 20)


# dict: Key-value pairs, like a map
person = {"name": "Alice", "age": 25}


# set: Unordered collection eith unique items
unique_numbers = {1, 2, 3, 4}


# Printing each data type to see the output
print("Age:", age)
print("Height:", height)
print("Greeting:", greeting)
print("Is Active:", is_active)
print("Fruits:", fruits)
print("Coordinates:", coordinates)
print("Person:", person)
print("Unique Numbers:", unique_numbers)
